version: "3.4"
services:
    web:
        build: 
            context: .
            dockerfile: "Content/WebApi/Dockerfile"
        ports:
            - "8000:8000"
            - "4433:4433"
        depends_on:
            - db
    db:
        image: "microsoft/mssql-server-linux"
        environment:
            SA_PASSWORD: "Passw0rd!"
            ACCEPT_EULA: "Y"